# Generated by Django 4.1.5 on 2023-01-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titel')),
                ('image', models.ImageField(upload_to='', verbose_name='Bild')),
                ('ingr', models.TextField(max_length=600, verbose_name='Zutaten')),
                ('instr', models.TextField(max_length=20000, verbose_name='Zubereitung')),
            ],
        ),
    ]
