# Generated by Django 4.1.5 on 2023-01-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0002_category_recipe_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos', models.ImageField(upload_to='', verbose_name='Bild')),
            ],
        ),
    ]
