# Generated by Django 4.1.5 on 2023-01-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezepte', '0003_fotos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fotos',
        ),
    ]
